
/**
 * Base for classes that provide access to the token distribution facilities
 */
class BaseFaucet {
  /**
   * Request the sending of tokens to a users address
   *
   * @param {string} authName the name of the authentication channel
   * @param {string} address the address of the account to send funds to
   * @param {string} jwt the JSON Web token generated by the auth channel
   * @param {string} signature resulting from the signing of the JWT by the address
   */
  async send ({ authName, address, jwt, signature }) {
    throw new Error('Subclass must override the send method')
  }
}

module.exports = BaseFaucet
