const BaseFaucet = require('./BaseFaucet')
const { Fetch } = require('../../service')

/**
 * Provides access to the token distribution facilities provided by the
 * hashed faucet server
 */
class HashedFaucet extends BaseFaucet {
  /**
   * @param {string} url of the hashed faucet server
   */
  constructor (url) {
    super()
    this._fetch = new Fetch(url)
  }

  /**
   * Request the sending of tokens to a users address
   *
   * @param {string} authName the name of the authentication channel
   * @param {string} address the address of the account to send funds to
   * @param {string} jwt the JSON Web token generated by the auth channel
   * @param {string} signature resulting from the signing of the JWT by the address
   */
  async send ({ authName, address, jwt, signature }) {
    // console.log(`Sending amount: ${this._amount} to address: ${address}`)
    return this._fetch.post('/api/distribution/distribute', {
      authName,
      address,
      jwt,
      signature
    })
  }
}

module.exports = HashedFaucet
